--
-- Table structure for table `raw_logs`
--

DROP TABLE IF EXISTS `raw_logs`;

CREATE TABLE `raw_logs` (
  `v` varchar(1) DEFAULT NULL,
  `session` varchar(15) NOT NULL DEFAULT '0',
  `id` varchar(32) NOT NULL DEFAULT '0',
  `time` varchar(15) NOT NULL DEFAULT '0',
  `eml` varchar(255) DEFAULT NULL,
  `profileName` varchar(255) NOT NULL DEFAULT '0',
  `profileFuelType` varchar(255) NOT NULL DEFAULT 'Not Specified',
  `profileWeight` float NOT NULL DEFAULT '0',
  `profileVe` float NOT NULL DEFAULT '0',
  `profileFuelCost` float NOT NULL DEFAULT '0',
  `notice` varchar(255) DEFAULT NULL,
  `noticeClass` varchar(255) DEFAULT NULL,
  `k10` float NOT NULL DEFAULT '0',
  `k11` float NOT NULL DEFAULT '0',
  `k12` float NOT NULL DEFAULT '0',
  `k14` float NOT NULL DEFAULT '0',
  `k15` float NOT NULL DEFAULT '0',
  `k16` float NOT NULL DEFAULT '0',
  `k17` float NOT NULL DEFAULT '0',
  `k18` float NOT NULL DEFAULT '0',
  `k19` float NOT NULL DEFAULT '0',
  `k1a` float NOT NULL DEFAULT '0',
  `k1b` float NOT NULL DEFAULT '0',
  `k1f` float NOT NULL DEFAULT '0',
  `k21` float NOT NULL DEFAULT '0',
  `k22` float NOT NULL DEFAULT '0',
  `k23` float NOT NULL DEFAULT '0',
  `k24` float NOT NULL DEFAULT '0',
  `k25` float NOT NULL DEFAULT '0',
  `k26` float NOT NULL DEFAULT '0',
  `k27` float NOT NULL DEFAULT '0',
  `k28` float NOT NULL DEFAULT '0',
  `k29` float NOT NULL DEFAULT '0',
  `k2a` float NOT NULL DEFAULT '0',
  `k2b` float NOT NULL DEFAULT '0',
  `k2c` float NOT NULL DEFAULT '0',
  `k2d` float NOT NULL DEFAULT '0',
  `k2f` float NOT NULL DEFAULT '0',
  `k3`  float NOT NULL DEFAULT '0',
  `k31` float NOT NULL DEFAULT '0',
  `k32` float NOT NULL DEFAULT '0',
  `k33` float NOT NULL DEFAULT '0',
  `k34` float NOT NULL DEFAULT '0',
  `k3c` float NOT NULL DEFAULT '0',
  `k3d` float NOT NULL DEFAULT '0',
  `k3e` float NOT NULL DEFAULT '0',
  `k3f` float NOT NULL DEFAULT '0',
  `k4`  float NOT NULL DEFAULT '0',
  `k42` float NOT NULL DEFAULT '0',
  `k43` float NOT NULL DEFAULT '0',
  `k44` float NOT NULL DEFAULT '0',
  `k45` float NOT NULL DEFAULT '0',
  `k46` float NOT NULL DEFAULT '0',
  `k47` float NOT NULL DEFAULT '0',
  `k49` float NOT NULL DEFAULT '0',
  `k4a` float NOT NULL DEFAULT '0',
  `k4b` float NOT NULL DEFAULT '0',
  `k5`  float NOT NULL DEFAULT '0',
  `k52` float NOT NULL DEFAULT '0',
  `k5a` float NOT NULL DEFAULT '0',
  `k5c` float NOT NULL DEFAULT '0',
  `k6`  float NOT NULL DEFAULT '0',
  `k7`  float NOT NULL DEFAULT '0',
  `k78` float NOT NULL DEFAULT '0',
  `k79` float NOT NULL DEFAULT '0',
  `k8`  float NOT NULL DEFAULT '0',
  `k9`  float NOT NULL DEFAULT '0',
  `ka`  float NOT NULL DEFAULT '0',
  `kb`  float NOT NULL DEFAULT '0',
  `kb4` float NOT NULL DEFAULT '0',
  `kc`  float NOT NULL DEFAULT '0',
  `kd`  float NOT NULL DEFAULT '0',
  `ke`  float NOT NULL DEFAULT '0',
  `kf`  float NOT NULL DEFAULT '0',
  `kfe1805` float NOT NULL DEFAULT '0',
  `kff1001` float NOT NULL DEFAULT '0',
  `kff1005` float NOT NULL DEFAULT '0',
  `kff1006` float NOT NULL DEFAULT '0',
  `kff1007` float NOT NULL DEFAULT '0',
  `kff1010` float NOT NULL DEFAULT '0',
  `kff1201` float NOT NULL DEFAULT '0',
  `kff1202` float NOT NULL DEFAULT '0',
  `kff1203` float NOT NULL DEFAULT '0',
  `kff1204` float NOT NULL DEFAULT '0',
  `kff1205` float NOT NULL DEFAULT '0',
  `kff1206` float NOT NULL DEFAULT '0',
  `kff1207` float NOT NULL DEFAULT '0',
  `kff1208` float NOT NULL DEFAULT '0',
  `kff120c` float NOT NULL DEFAULT '0',
  `kff1214` float NOT NULL DEFAULT '0',
  `kff1215` float NOT NULL DEFAULT '0',
  `kff1216` float NOT NULL DEFAULT '0',
  `kff1217` float NOT NULL DEFAULT '0',
  `kff1218` float NOT NULL DEFAULT '0',
  `kff1219` float NOT NULL DEFAULT '0',
  `kff121a` float NOT NULL DEFAULT '0',
  `kff121b` float NOT NULL DEFAULT '0',
  `kff1220` float NOT NULL DEFAULT '0',
  `kff1221` float NOT NULL DEFAULT '0',
  `kff1222` float NOT NULL DEFAULT '0',
  `kff1223` float NOT NULL DEFAULT '0',
  `kff1225` float NOT NULL DEFAULT '0',
  `kff1226` float NOT NULL DEFAULT '0',
  `kff122d` float NOT NULL DEFAULT '0',
  `kff122e` float NOT NULL DEFAULT '0',
  `kff122f` float NOT NULL DEFAULT '0',
  `kff1230` float NOT NULL DEFAULT '0',
  `kff1237` float NOT NULL DEFAULT '0',
  `kff1238` float NOT NULL DEFAULT '0',
  `kff1239` float NOT NULL DEFAULT '0',
  `kff123a` float NOT NULL DEFAULT '0',
  `kff123b` float NOT NULL DEFAULT '0',
  `kff1240` float NOT NULL DEFAULT '0',
  `kff1241` float NOT NULL DEFAULT '0',
  `kff1242` float NOT NULL DEFAULT '0',
  `kff1243` float NOT NULL DEFAULT '0',
  `kff1244` float NOT NULL DEFAULT '0',
  `kff1245` float NOT NULL DEFAULT '0',
  `kff1246` float NOT NULL DEFAULT '0',
  `kff1247` float NOT NULL DEFAULT '0',
  `kff1249` float NOT NULL DEFAULT '0',
  `kff124a` float NOT NULL DEFAULT '0',
  `kff124b` float NOT NULL DEFAULT '0',
  `kff124c` float NOT NULL DEFAULT '0',
  `kff124d` float NOT NULL DEFAULT '0',
  `kff124f` float NOT NULL DEFAULT '0',
  `kff1257` float NOT NULL DEFAULT '0',
  `kff1258` float NOT NULL DEFAULT '0',
  `kff125a` float NOT NULL DEFAULT '0',
  `kff125c` float NOT NULL DEFAULT '0',
  `kff125d` float NOT NULL DEFAULT '0',
  `kff125e` float NOT NULL DEFAULT '0',
  `kff125f` float NOT NULL DEFAULT '0',
  `kff1260` float NOT NULL DEFAULT '0',
  `kff1261` float NOT NULL DEFAULT '0',
  `kff1263` float NOT NULL DEFAULT '0',
  `kff1264` float NOT NULL DEFAULT '0',
  `kff1265` float NOT NULL DEFAULT '0',
  `kff1266` float NOT NULL DEFAULT '0',
  `kff1267` float NOT NULL DEFAULT '0',
  `kff1268` float NOT NULL DEFAULT '0',
  `kff1269` float NOT NULL DEFAULT '0',
  `kff126a` float NOT NULL DEFAULT '0',
  `kff126b` float NOT NULL DEFAULT '0',
  `kff126d` float NOT NULL DEFAULT '0',
  `kff126e` float NOT NULL DEFAULT '0',
  `kff1270` float NOT NULL DEFAULT '0',
  `kff1271` float NOT NULL DEFAULT '0',
  `kff1272` float NOT NULL DEFAULT '0',
  `kff1273` float NOT NULL DEFAULT '0',
  `kff1275` float NOT NULL DEFAULT '0',
  `kff1276` float NOT NULL DEFAULT '0',
  `kff1277` float NOT NULL DEFAULT '0',
  `kff5201` float NOT NULL DEFAULT '0',
  `kff5202` float NOT NULL DEFAULT '0',
  `kff5203` float NOT NULL DEFAULT '0',
  KEY `session` (`session`,`id`),
  KEY `id` (`id`)
) DEFAULT CHARSET=utf8;

--
-- Table structure for table `sessions`
--

DROP TABLE IF EXISTS `sessions`;
CREATE TABLE `sessions` (
  `v` varchar(1) DEFAULT NULL,
  `id` varchar(32) NOT NULL DEFAULT '0',
  `session` varchar(15) NOT NULL DEFAULT '0',
  `time` varchar(15) DEFAULT '0',
  `eml` varchar(255) NOT NULL DEFAULT '0',
  `profileName` varchar(255) NOT NULL DEFAULT 'Not Specified',
  `profileFuelType` varchar(255) NOT NULL DEFAULT 'Not Specified',
  `profileWeight` float NOT NULL DEFAULT '0',
  `profileVe` float NOT NULL DEFAULT '0',
  `profileFuelCost` float NOT NULL DEFAULT '0',
  `timestart` varchar(15) DEFAULT NULL,
  `timeend` varchar(15) DEFAULT NULL,
  `sessionsize` varchar(15) NOT NULL DEFAULT '0',
  UNIQUE KEY `session` (`session`,`id`),
  KEY `id` (`id`)
) DEFAULT CHARSET=utf8;

--
-- Table structure for table `torque_keys`
--

DROP TABLE IF EXISTS `torque_keys`;

CREATE TABLE `torque_keys` (
  `id` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL COMMENT 'Description',
  `type` varchar(255) NOT NULL DEFAULT 'varchar(255)' COMMENT 'Variable Type',
  `units` varchar(255) DEFAULT NULL COMMENT 'Units',
  `populated` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'Is This Variable Populated?',
  `min` float DEFAULT NULL COMMENT 'Minimum Value',
  `max` float DEFAULT NULL COMMENT 'Maximum Value',
  UNIQUE KEY `id` (`id`) USING BTREE
) DEFAULT CHARSET=utf8;


LOCK TABLES `torque_keys` WRITE;

INSERT INTO `torque_keys` VALUES
  ('k10', 'Mass Air Flow Rate', 'float', NULL, 1, NULL, NULL),
  ('k11', 'Throttle Position (Manifold)', 'float', '%', 1, 0, 100), ('k12', 'Air Status', 'float', NULL, 1, NULL, NULL),
  ('k14', 'Fuel Trim Bank 1 Sensor 1', 'float', '%', 1, -100, 100),
  ('k15', 'Fuel Trim Bank 1 Sensor 2', 'float', '%', 1, NULL, NULL),
  ('k16', 'Fuel Trim Bank 1 Sensor 3', 'float', '%', 1, NULL, NULL),
  ('k17', 'Fuel Trim Bank 1 Sensor 4', 'float', '%', 1, NULL, NULL),
  ('k18', 'Fuel Trim Bank 2 Sensor 1', 'float', '%', 1, -100, 100),
  ('k19', 'Fuel Trim Bank 2 Sensor 2', 'float', '%', 1, NULL, NULL),
  ('k1a', 'Fuel Trim Bank 2 Sensor 3', 'float', '%', 1, NULL, NULL),
  ('k1b', 'Fuel Trim Bank 2 Sensor 4', 'float', '%', 1, NULL, NULL),
  ('k1f', 'Run Time Since Engine Start', 'float', 's', 1, 0, 100),
  ('k21', 'Distance Travelled With MIL/CEL Lit', 'float', 'km', 1, 0, 100),
  ('k22', 'Fuel Rail Pressure (Relative to Manifold Vacuum)', 'float', NULL, 1, NULL, NULL),
  ('k23', 'Fuel Rail Pressure', 'float', NULL, 1, NULL, NULL),
  ('k24', 'O2 Sensor1 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k25', 'O2 Sensor2 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k26', 'O2 Sensor3 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k27', 'O2 Sensor4 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k28', 'O2 Sensor5 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k29', 'O2 Sensor6 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k2a', 'O2 Sensor7 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k2b', 'O2 Sensor8 Equivalence Ratio', 'float', NULL, 1, NULL, NULL),
  ('k2c', 'EGR Commanded', 'float', NULL, 1, NULL, NULL), ('k2d', 'EGR Error', 'float', NULL, 1, NULL, NULL),
  ('k2f', 'Fuel Level (From Engine ECU)', 'float', '%', 1, 0, 100), ('k3', 'Fuel Status', 'float', NULL, 1, NULL, NULL),
  ('k31', 'Distance Travelled Since Codes Cleared', 'float', 'km', 1, 0, 100),
  ('k32', 'Evap System Vapor Pressure', 'float', 'Pa', 1, 0, 1000),
  ('k33', 'Barometric Pressure (From Vehicle)', 'float', 'kPa', 1, 0, 255),
  ('k34', 'O2 Sensor1 Equivalence Ratio (Alternate)', 'float', NULL, 1, NULL, NULL),
  ('k3c', 'Catalyst Temperature (Bank 1 Sensor 1)', 'float', '&deg;C', 1, 0, 60),
  ('k3d', 'Catalyst Temperature (Bank 2 Sensor 1)', 'float', '&deg;C', 1, 0, 60),
  ('k3e', 'Catalyst Temperature (Bank 1 Sensor 2)', 'float', '&deg;C', 1, NULL, NULL),
  ('k3f', 'Catalyst Temperature (Bank 2 Sensor 2)', 'float', '&deg;C', 1, NULL, NULL),
  ('k4', 'Engine Load', 'float', '%', 1, 0, 100), ('k42', 'Voltage (Control Module)', 'float', 'V', 1, 0, 16),
  ('k43', 'Engine Load (Absolute)', 'float', '%', 1, 0, 20000),
  ('k44', 'Commanded Equivalence Ratio (lambda)', 'float', NULL, 1, 0, 2),
  ('k45', 'Relative Throttle Position', 'float', '%', 1, 0, 100),
  ('k46', 'Ambient Air Temp', 'float', '&deg;C', 1, -40, 50),
  ('k47', 'Absolute Throttle Position B', 'float', '%', 1, 0, 100),
  ('k49', 'Accelerator Pedal Position D', 'float', '%', 1, 0, 100),
  ('k4a', 'Accelerator Pedal Position E', 'float', '%', 1, 0, 100),
  ('k4b', 'Accelerator Pedal Position F', 'float', '%', 1, 0, 100),
  ('k5', 'Engine Coolant Temperature', 'float', '&deg;C', 1, -40, 120),
  ('k52', 'Ethanol Fuel %', 'float', '%', 1, NULL, NULL),
  ('k5a', 'Relative Accelerator Pedal Position', 'float', '%', 1, NULL, NULL),
  ('k5c', 'Engine Oil Temperature', 'float', '&deg;C', 1, NULL, NULL),
  ('k6', 'Fuel Trim Bank 1 Short Term', 'float', '%', 1, -25, 25),
  ('k7', 'Fuel Trim Bank 1 Long Term', 'float', '%', 1, -25, 25),
  ('k78', 'Exhaust Gas Temperature 1', 'float', '&deg;C', 1, NULL, NULL),
  ('k79', 'Exhaust Gas Temperature 2', 'float', '&deg;C', 1, NULL, NULL),
  ('k8', 'Fuel Trim Bank 2 Short Term', 'float', '%', 1, -25, 25),
  ('k9', 'Fuel Trim Bank 2 Long Term', 'float', '%', 1, -25, 25), ('ka', 'Fuel Pressure', 'float', NULL, 1, NULL, NULL),
  ('kb', 'Intake Manifold Pressure', 'float', 'kPa', 1, 0, 255),
  ('kb4', 'Transmission Temperature (Method 2)', 'float', '&deg;C', 1, NULL, NULL),
  ('kc', 'Engine RPM', 'float', 'rpm', 1, 0, 10000), ('kd', 'Speed (OBD)', 'float', 'km/h', 1, 0, 160),
  ('ke', 'Timing Advance', 'float', '&deg;', 1, -64, 63),
  ('kf', 'Intake Air Temperature', 'float', '&deg;C', 1, -40, 60),
  ('kfe1805', 'Transmission Temperature (Method 1)', 'float', '&deg;C', 1, NULL, NULL),
  ('kff1001', 'Speed (GPS)', 'float', 'km/h', 1, 0, 160), ('kff1005', 'GPS Longitude', 'float', '&deg;', 1, 0, 100),
  ('kff1006', 'GPS Latitude', 'float', '&deg;', 1, 0, 100), ('kff1007', 'GPS Bearing', 'float', '&deg;', 1, 0, 360),
  ('kff1010', 'GPS Altitude', 'float', 'm', 1, 0, 100),
  ('kff1201', 'Miles Per Gallon (Instant)', 'float', 'mpg', 1, 0, 100),
  ('kff1202', 'Turbo Boost & Vacuum Gauge', 'float', 'psi', 1, -20, 20),
  ('kff1203', 'Kilometers Per Litre (Instant)', 'float', 'kpl', 1, 0, 100),
  ('kff1204', 'Trip Distance', 'float', 'km', 1, 0, 200), ('kff1205', 'Trip Average MPG', 'float', 'mpg', 1, 0, 100),
  ('kff1206', 'Trip Average KPL', 'float', 'kpl', 1, 0, 100),
  ('kff1207', 'Litres Per 100 Kilometer (Instant)', 'float', 'l/100km', 1, 0, 100),
  ('kff1208', 'Trip Average Litres/100 KM', 'float', 'l/100km', 1, 0, 100),
  ('kff120c', 'Trip Distance (Stored in Vehicle Profile)', 'float', 'km', 1, 0, 100),
  ('kff1214', 'O2 Volts Bank 1 Sensor 1', 'float', 'V', 1, 0, 1),
  ('kff1215', 'O2 Volts Bank 1 Sensor 2', 'float', 'V', 1, 0, 1),
  ('kff1216', 'O2 Volts Bank 1 Sensor 3', 'float', 'V', 1, NULL, NULL),
  ('kff1217', 'O2 Volts Bank 1 Sensor 4', 'float', 'V', 1, NULL, NULL),
  ('kff1218', 'O2 Volts Bank 2 Sensor 1', 'float', 'V', 1, 0, 1),
  ('kff1219', 'O2 Volts Bank 2 Sensor 2', 'float', 'V', 1, 0, 1),
  ('kff121a', 'O2 Volts Bank 2 Sensor 3', 'float', 'V', 1, NULL, NULL),
  ('kff121b', 'O2 Volts Bank 2 Sensor 4', 'float', 'V', 1, NULL, NULL),
  ('kff1220', 'Acceleration Sensor (X Axis)', 'float', 'g', 1, -1, 1),
  ('kff1221', 'Acceleration Sensor (Y Axis)', 'float', 'g', 1, -1, 1),
  ('kff1222', 'Acceleration Sensor (Z Axis)', 'float', 'g', 1, -1, 1),
  ('kff1223', 'Acceleration Sensor (Total)', 'float', 'g', 1, -1, 1),
  ('kff1225', 'Torque', 'float', 'ft-lb', 1, 0, 100),
  ('kff1226', 'Horsepower (At the Wheels)', 'float', 'hp', 1, 0, 100),
  ('kff122d', '0-60mph Time', 'float', 's', 1, 0, 16), ('kff122e', '0-100kph Time', 'float', 's', 1, 0, 16),
  ('kff122f', '1/4 mile Time', 'float', 's', 1, 0, 30), ('kff1230', '1/8 mile Time', 'float', 's', 1, 0, 16),
  ('kff1237', 'GPS vs OBD Speed Difference', 'float', 'km/h', 1, 0, 10),
  ('kff1238', 'Voltage (OBD Adapter)', 'float', 'V', 1, 0, 16), ('kff1239', 'GPS Accuracy', 'float', 'm', 1, 0, 100),
  ('kff123a', 'GPS Satellites', 'float', NULL, 1, 0, 10), ('kff123b', 'GPS Bearing', 'float', '&deg;', 1, 0, 360),
  ('kff1240', 'O2 Sensor1 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1241', 'O2 Sensor2 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1242', 'O2 Sensor3 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1243', 'O2 Sensor4 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1244', 'O2 Sensor5 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1245', 'O2 Sensor6 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1246', 'O2 Sensor7 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1247', 'O2 Sensor8 Wide-range Voltage', 'float', 'V', 1, NULL, NULL),
  ('kff1249', 'Air Fuel Ratio (Measured)', 'float', NULL, 1, NULL, NULL),
  ('kff124a', 'Tilt (x)', 'float', NULL, 1, NULL, NULL), ('kff124b', 'Tilt (y)', 'float', NULL, 1, NULL, NULL),
  ('kff124c', 'Tilt (z)', 'float', NULL, 1, NULL, NULL),
  ('kff124d', 'Air Fuel Ratio (Commanded)', 'float', NULL, 1, 0, 30),
  ('kff124f', '0-200kph Time', 'float', 's', 1, 0, 16), ('kff1257', 'CO2 (Instantaneous)', 'float', 'g/km', 1, 0, 120),
  ('kff1258', 'CO2 (Average)', 'float', 'g/km', 1, 0, 120),
  ('kff125a', 'Fuel Flow Rate/Minute', 'float', 'cc/min', 1, 0, 100),
  ('kff125c', 'Fuel Cost (Trip)', 'float', '$', 1, 0, 100),
  ('kff125d', 'Fuel Flow Rate/Hour', 'float', 'l/hr', 1, 0, 100), ('kff125e', '60-120mph Time', 'float', 's', 1, 0, 16),
  ('kff125f', '60-80mph Time', 'float', 's', 1, 0, 16), ('kff1260', '40-60mph Time', 'float', 's', 1, 0, 16),
  ('kff1261', '80-100mph Time', 'float', 's', 1, 0, 16),
  ('kff1263', 'Average Trip Speed (Whilst Moving Only)', 'float', 'km/h', 1, 0, 16),
  ('kff1264', '100-0kph Time', 'float', 's', 1, 0, 16), ('kff1265', '60-0mph Time', 'float', 's', 1, 0, 16),
  ('kff1266', 'Trip Time (Since Journey Start)', 'float', 's', 1, 0, 100),
  ('kff1267', 'Trip Time (Whilst Stationary)', 'float', 's', 1, 0, 100),
  ('kff1268', 'Trip Time (Whilst Moving)', 'float', 's', 1, 0, 100),
  ('kff1269', 'Volumetric Efficiency (Calculated)', 'float', '%', 1, NULL, NULL),
  ('kff126a', 'Distance to empty (Estimated)', 'float', 'km', 1, 0, 100),
  ('kff126b', 'Fuel Remaining (Calculated From Vehicle Profile)', 'float', '%', 1, 0, 100),
  ('kff126d', 'Cost per mile/km (Instant)', 'float', '$/km', 1, 0, 100),
  ('kff126e', 'Cost per mile/km (Trip)', 'float', '$/km', 1, 0, 100),
  ('kff1270', 'Barometer (On Android device)', 'float', 'mb', 1, 800, 1100),
  ('kff1271', 'Fuel Used (Trip)', 'float', 'l', 1, 0, 100),
  ('kff1272', 'Average Trip Speed (Whilst Stopped or Moving)', 'float', 'km/h', 1, 0, 16),
  ('kff1273', 'Engine kW (At the Wheels)', 'float', 'kW', 1, 0, 100),
  ('kff1275', '80-120kph Time', 'float', 's', 1, 0, 16), ('kff1276', '60-130mph Time', 'float', 's', 1, 0, 16),
  ('kff1277', '0-30mph Time', 'float', 's', 1, 0, 16),
  ('kff1296', 'Percentage of City driving', 'float', '%', 1, 0, 100),
  ('kff1297', 'Percentage of Highway driving', 'float', '%', 1, 0, 100),
  ('kff1298', 'Percentage of Idle driving', 'float', '%', 1, 0, 100),
  ('kff5201', 'Miles Per Gallon (Long Term Average)', 'float', 'mpg', 1, 0, 100),
  ('kff5202', 'Kilometers Per Litre (Long Term Average)', 'float', 'kpl', 1, 0, 100),
  ('kff5203', 'Litres Per 100 Kilometer (Long Term Average)', 'float', 'l/100km', 1, 0, 100),
  ('session', 'Session ID', 'varchar(255)', NULL, 1, NULL, NULL),
  ('time', 'Timestamp', 'varchar(255)', NULL, 1, NULL, NULL);

UNLOCK TABLES;